#include <iostream>
#include <chrono>
#include <vector>
#include <algorithm>
#include <ctime>
using namespace std;

void selectionSort(vector<int>& arr, int n) {
    for (int i = 0; i < n - 1; i++) { // n-1 number of passes
        int minIdx = i; // let this be the index of the min element
        for (int j = i + 1; j < n; j++) { // compare with all the succeeding elements of the array
            if (arr[j] < arr[minIdx])
                minIdx = j;
        }
        swap(arr[minIdx], arr[i]);
    }
}

void inputGenerator(vector<pair<int, int>>& store) {
    for (int i = 10; i <= 10000; i += 1000) {
        vector<int> arr(i);
        generate(arr.begin(), arr.end(), rand);

        clock_t timeStart, timeEnd;
        int totalTime = 0;
        for (int m = 1; m <= 10; m++) {
            timeStart = clock();
            selectionSort(arr, i);
            timeEnd = clock();
            totalTime += (timeEnd - timeStart);
        }
        int averageTime = totalTime / 10;
        store.push_back({ averageTime, i });
    }
}

int main() {
    vector<pair<int, int>> store;
    inputGenerator(store);

    cout << "Time" << "\t" << "Number of Inputs" << endl;
    for (const auto& i : store) {
        cout << i.first << "\t" << i.second << endl;
    }

    return 0;
}

// Description about the code
/*
    Analysing the time complexity of Selection Sort.
    1. Taking varied inputs in the array (generating the inputs using generate function:- generate(arr.begin(),arr.end(),rand)). 
    Made an input generator function which reapeated generates the asked number of inputs.
    2. Running Selection sort for the generated outputs for 10 times and taking average of that time.
    3.Plotting the graph between number of inputs and the time taken.
    
    As complexity of selection sort is of the order of n^2 we get a parabolic graph.
    (Graph plotted in desmos)
*/

// scale up and scale down of time
//CLOCKS_PER_SEC macro for converting the time generated by clock into seconds
